import type { Brand } from './lendersData';

export const autoLoansData: Brand[] = [
  {
    id: 1,
    name: 'SoFi',
    logo: '/images/table/Sofi-logo.svg',
    ourScore: 9.7,
    trustpilotScore: 9.2,
    brandReputation: 9.8,
    popularityScore: 9.6,
    reviewCount: 12500,
    highlight: 'Low rates and fast pre-approval for auto loans',
    productTypes: ['new', 'used'],
    minCreditScore: 'good',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '15k_30k',
    amount: '$5K - $100K',
    goodDetails: [
      'Rate Range: 2.99% - 14.99%',
      'No Fees: Yes',
      'Fast Pre-approval: 24 hours',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 680',
      'Income Requirement: $45,000+',
      'Vehicle Age: Up to 10 years',
      'Loan Term: 24-84 months',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 2,
    name: 'LightStream',
    logo: '/images/table/LightStream-logo.svg',
    ourScore: 9.6,
    trustpilotScore: 9.4,
    brandReputation: 9.6,
    popularityScore: 9.4,
    reviewCount: 9800,
    highlight: 'Best rates for borrowers with excellent credit',
    productTypes: ['new', 'used'],
    minCreditScore: 'excellent',
    minRevenue: '20k_30k',
    minTimeInBusiness: '1_2',
    amountRange: '30k_50k',
    amount: '$5K - $100K',
    goodDetails: [
      'Rate Range: 2.49% - 12.99%',
      'No Fees: Yes',
      'Same-Day Funding: Available',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 720',
      'Income Requirement: $50,000+',
      'Vehicle Age: Up to 10 years',
      'Co-signers: Not allowed',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 3,
    name: 'LendingTree',
    logo: '/images/table/LendingTree-logo.svg',
    ourScore: 9.5,
    trustpilotScore: 9.1,
    brandReputation: 9.5,
    popularityScore: 9.3,
    reviewCount: 15200,
    highlight: 'Compare auto loan rates from multiple lenders',
    productTypes: ['new', 'used', 'refinance'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '15k_30k',
    amount: '$5K - $100K',
    goodDetails: [
      'Multiple Offers: Yes',
      'All Vehicle Types: Available',
      'Rate Comparison: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 600',
      'APR Range: 2.99% - 24.99%',
      'Vehicle Age: Varies by lender',
      'Loan Term: 24-84 months',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 4,
    name: 'Credible',
    logo: '/images/table/Credible-logo.svg',
    ourScore: 9.4,
    trustpilotScore: 9.0,
    brandReputation: 9.4,
    popularityScore: 9.2,
    reviewCount: 11200,
    highlight: 'Compare prequalified auto loan rates',
    productTypes: ['new', 'used'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '15k_30k',
    amount: '$5K - $100K',
    goodDetails: [
      'Prequalification: No hard pull',
      'Multiple Lenders: Yes',
      'Rate Comparison: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 600',
      'APR Range: 2.99% - 24.99%',
      'Vehicle Age: Up to 10 years',
      'Loan Term: 24-84 months',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 5,
    name: 'NerdWallet',
    logo: '/images/brands-logos/nerd-wallet-logo.svg',
    ourScore: 9.3,
    trustpilotScore: 8.8,
    brandReputation: 9.6,
    popularityScore: 9.5,
    reviewCount: 18500,
    highlight: 'Expert guidance to find the best auto loan',
    productTypes: ['new', 'used', 'refinance'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '15k_30k',
    amount: '$5K - $100K',
    goodDetails: [
      'Expert Reviews: Yes',
      'Comparison Tools: Yes',
      'Educational Resources: Yes',
      'Free Service: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 600',
      'APR Range: Varies by lender',
      'Not a Direct Lender: Marketplace',
      'Loan Term: Varies by lender',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 6,
    name: 'Fundera',
    logo: '/images/brands-logos/fundera-logo.svg',
    ourScore: 9.2,
    trustpilotScore: 9.0,
    brandReputation: 9.2,
    popularityScore: 9.0,
    reviewCount: 8400,
    highlight: 'Expert guidance to find the best auto loan rates',
    productTypes: ['new', 'used'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '15k_30k',
    amount: '$5K - $100K',
    goodDetails: [
      'Expert Guidance: Yes',
      'Multiple Lenders: Yes',
      'Rate Comparison: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 600',
      'APR Range: 2.99% - 24.99%',
      'Vehicle Age: Up to 10 years',
      'Loan Term: 24-84 months',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 7,
    name: 'Lendio',
    logo: '/images/brands-logos/lendio-logo.svg',
    ourScore: 9.1,
    trustpilotScore: 8.6,
    brandReputation: 9.0,
    popularityScore: 8.8,
    reviewCount: 9200,
    highlight: 'Access to multiple auto loan lenders',
    productTypes: ['new', 'used', 'refinance'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '15k_30k',
    amount: '$5K - $100K',
    goodDetails: [
      'Multiple Lenders: Yes',
      'One Application: Yes',
      'Fast Matching: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 600',
      'APR Range: 2.99% - 24.99%',
      'Vehicle Age: Varies by lender',
      'Loan Term: 24-84 months',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 8,
    name: 'Biz2Credit',
    logo: '/images/brands-logos/Biz2credit-logo.svg',
    ourScore: 9.0,
    trustpilotScore: 9.4,
    brandReputation: 9.7,
    popularityScore: 9.6,
    reviewCount: 15146,
    highlight: 'Fast approval for auto loan refinancing',
    productTypes: ['refinance'],
    minCreditScore: 'good',
    minRevenue: '20k_30k',
    minTimeInBusiness: '1_2',
    amountRange: '30k_50k',
    amount: '$10K - $100K',
    goodDetails: [
      'Fast Approval: 24 hours',
      'Competitive Rates: Yes',
      'No Fees: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 650',
      'Income Requirement: $50,000+',
      'Vehicle Age: Up to 10 years',
      'Existing Loan: Must qualify',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
];
