import type { Brand } from './lendersData';

export const goldAndSilverData: Brand[] = [
  {
    id: 1,
    name: 'APMEX',
    logo: null,
    ourScore: 9.7,
    trustpilotScore: 9.3,
    brandReputation: 9.6,
    popularityScore: 9.5,
    reviewCount: 18500,
    highlight: 'Largest online precious metals dealer with extensive selection',
    productTypes: ['gold', 'silver'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '1k_5k',
    amount: '$25 - $500K+',
    goodDetails: [
      'Selection: Extensive',
      'IRA Eligible: Yes',
      'Vault Storage: Available',
      'Online Ordering: Yes',
    ],
    badDetails: [
      'Minimum Order: $25',
      'Premium: Varies by product',
      'Shipping: Fees apply',
      'Storage Fees: For vault storage',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 2,
    name: 'JM Bullion',
    logo: null,
    ourScore: 9.6,
    trustpilotScore: 9.2,
    brandReputation: 9.5,
    popularityScore: 9.4,
    reviewCount: 15200,
    highlight: 'Competitive prices and fast shipping on precious metals',
    productTypes: ['gold', 'silver'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '1k_5k',
    amount: '$50 - $500K+',
    goodDetails: [
      'Selection: Wide variety',
      'Competitive Prices: Yes',
      'Fast Shipping: Yes',
      'Online Ordering: Yes',
    ],
    badDetails: [
      'Minimum Order: $50',
      'Premium: Varies by product',
      'Shipping: Fees apply',
      'Storage: Home only',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 3,
    name: 'Goldco',
    logo: null,
    ourScore: 9.5,
    trustpilotScore: 9.1,
    brandReputation: 9.4,
    popularityScore: 9.3,
    reviewCount: 12800,
    highlight: 'Best for precious metals IRAs and retirement planning',
    productTypes: ['gold', 'silver', 'platinum'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '5k_25k',
    amount: '$25K - $500K',
    goodDetails: [
      'IRA Services: Yes',
      'Expert Guidance: Yes',
      'Vault Storage: Available',
      'Online Ordering: Yes',
    ],
    badDetails: [
      'Minimum Investment: $25,000',
      'Setup Fees: Apply',
      'Storage Fees: Annual',
      'Premium: Higher for IRA',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 4,
    name: 'Birch Gold Group',
    logo: null,
    ourScore: 9.4,
    trustpilotScore: 9.0,
    brandReputation: 9.3,
    popularityScore: 9.2,
    reviewCount: 11200,
    highlight: 'Expert guidance for precious metals IRAs',
    productTypes: ['gold', 'silver', 'platinum', 'palladium'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '5k_25k',
    amount: '$10K - $500K',
    goodDetails: [
      'IRA Services: Yes',
      'Expert Guidance: Yes',
      'Vault Storage: Available',
      'Multiple Metals: Yes',
    ],
    badDetails: [
      'Minimum Investment: $10,000',
      'Setup Fees: Apply',
      'Storage Fees: Annual',
      'Premium: Higher for IRA',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 5,
    name: 'Provident Metals',
    logo: null,
    ourScore: 9.3,
    trustpilotScore: 8.9,
    brandReputation: 9.2,
    popularityScore: 9.1,
    reviewCount: 9800,
    highlight: 'Competitive prices on gold and silver coins',
    productTypes: ['gold', 'silver'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '1k_5k',
    amount: '$100 - $500K+',
    goodDetails: [
      'Selection: Coins & bars',
      'Competitive Prices: Yes',
      'Fast Shipping: Yes',
      'Online Ordering: Yes',
    ],
    badDetails: [
      'Minimum Order: $100',
      'Premium: Varies by product',
      'Shipping: Fees apply',
      'Storage: Home only',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 6,
    name: 'SD Bullion',
    logo: null,
    ourScore: 9.2,
    trustpilotScore: 8.8,
    brandReputation: 9.1,
    popularityScore: 9.0,
    reviewCount: 8700,
    highlight: 'Low premiums on gold and silver bullion',
    productTypes: ['gold', 'silver'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '1k_5k',
    amount: '$50 - $500K+',
    goodDetails: [
      'Low Premiums: Yes',
      'Selection: Wide variety',
      'Fast Shipping: Yes',
      'Online Ordering: Yes',
    ],
    badDetails: [
      'Minimum Order: $50',
      'Premium: Varies by product',
      'Shipping: Fees apply',
      'Storage: Home only',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 7,
    name: 'Augusta Precious Metals',
    logo: null,
    ourScore: 9.1,
    trustpilotScore: 9.2,
    brandReputation: 9.3,
    popularityScore: 9.1,
    reviewCount: 10200,
    highlight: 'Best for high-net-worth precious metals IRAs',
    productTypes: ['gold', 'silver', 'platinum'],
    minCreditScore: 'good',
    minRevenue: 'more_30k',
    minTimeInBusiness: '2_plus',
    amountRange: '25k_plus',
    amount: '$50K - $1M+',
    goodDetails: [
      'IRA Services: Yes',
      'High-Value Accounts: Yes',
      'Expert Guidance: Yes',
      'Vault Storage: Available',
    ],
    badDetails: [
      'Minimum Investment: $50,000',
      'Setup Fees: Apply',
      'Storage Fees: Annual',
      'Premium: Higher for IRA',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 8,
    name: 'Money Metals Exchange',
    logo: null,
    ourScore: 9.0,
    trustpilotScore: 8.7,
    brandReputation: 9.0,
    popularityScore: 8.9,
    reviewCount: 7500,
    highlight: 'Competitive prices and educational resources',
    productTypes: ['gold', 'silver'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '1k_5k',
    amount: '$100 - $500K+',
    goodDetails: [
      'Competitive Prices: Yes',
      'Educational Resources: Yes',
      'Fast Shipping: Yes',
      'Online Ordering: Yes',
    ],
    badDetails: [
      'Minimum Order: $100',
      'Premium: Varies by product',
      'Shipping: Fees apply',
      'Storage: Home only',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
];
