// Lender data - easily swappable with real JSON data
export interface Lender {
  id: number;
  name: string;
  logo: string | null;
  totalScore: number;
  trustpilotScore: number | null;
  brandReputation: number | null;
  popularityScore: number | null;
  reviewCount: number | null;
  highlight: string;
  loanTypes: string[];
  minCreditScore: string;
  minRevenue: string;
  minTimeInBusiness: string;
  loanAmountRange: string;
  details: string[];
  ctaUrl: string;
  websiteUrl: string;
}

export const lendersData: Lender[] = [
  {
    id: 1,
    name: 'Biz2Credit',
    logo: '/images/brands-logos/Biz2credit-logo.svg',
    totalScore: 9.7,
    trustpilotScore: 9.4,
    brandReputation: 9.7,
    popularityScore: 9.6,
    reviewCount: 15146,
    highlight: 'Cash in the next 24hrs after approval',
    loanTypes: ['business_loan', 'working_capital', 'line_of_credit'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '50k_100k',
    details: [
      'Loan Amount: $25K - $6M',
      'Time in Business: 18+ months',
      'Average Monthly Revenue: At least $20,000',
      'Minimum Credit Score: 600',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 2,
    name: 'Fundera',
    logo: '/images/brands-logos/fundera-logo.svg',
    totalScore: 9.5,
    trustpilotScore: 9.2,
    brandReputation: 9.6,
    popularityScore: 9.4,
    reviewCount: 8234,
    highlight: 'Expert guidance to find the best loan for your business',
    loanTypes: ['business_loan', 'sba', 'line_of_credit'],
    minCreditScore: 'good',
    minRevenue: '20k_30k',
    minTimeInBusiness: '1_2',
    loanAmountRange: '50k_100k',
    details: [
      'Loan Amount: $5K - $5M',
      'Time in Business: 12+ months',
      'Annual Revenue: At least $100,000',
      'Minimum Credit Score: 650',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 3,
    name: 'SoFi',
    logo: '/images/table/Sofi-logo.svg',
    totalScore: 9.5,
    trustpilotScore: 8.6,
    brandReputation: 10,
    popularityScore: 10,
    reviewCount: 9665,
    highlight: 'Industry-leading digital banking experience with competitive rates',
    loanTypes: ['business_loan', 'sba'],
    minCreditScore: 'good',
    minRevenue: 'more_30k',
    minTimeInBusiness: '2_plus',
    loanAmountRange: '100k_plus',
    details: [
      'Loan Amount: $5K - $5M',
      'Time in Business: 24+ months',
      'Annual Revenue: At least $150,000',
      'Minimum Credit Score: 680',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 4,
    name: 'LendingTree',
    logo: '/images/table/LendingTree-logo.svg',
    totalScore: 9.4,
    trustpilotScore: 9.1,
    brandReputation: 9.5,
    popularityScore: 9.3,
    reviewCount: 12456,
    highlight: 'Compare multiple loan offers from top lenders in one place',
    loanTypes: ['business_loan', 'line_of_credit', 'sba'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '50k_100k',
    details: [
      'Loan Amount: $5K - $500K',
      'Time in Business: 6+ months',
      'Monthly Revenue: At least $10,000',
      'Minimum Credit Score: 600',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 5,
    name: 'Fundbox',
    logo: '/images/brands-logos/fund-box.svg',
    totalScore: 9.2,
    trustpilotScore: 9.2,
    brandReputation: 8.8,
    popularityScore: 9.0,
    reviewCount: 3421,
    highlight: 'Fast approval with flexible credit lines for growing businesses',
    loanTypes: ['line_of_credit', 'working_capital'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '10k_50k',
    details: [
      'Credit Line: $1K - $150K',
      'Time in Business: 6+ months',
      'Annual Revenue: At least $50,000',
      'Minimum Credit Score: 600',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 6,
    name: 'Lendio',
    logo: '/images/brands-logos/lendio-logo.svg',
    totalScore: 9.1,
    trustpilotScore: 9.0,
    brandReputation: 9.0,
    popularityScore: 8.9,
    reviewCount: 4567,
    highlight: 'Access to 75+ lenders with one simple application',
    loanTypes: ['business_loan', 'line_of_credit', 'sba', 'working_capital'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '50k_100k',
    details: [
      'Loan Amount: $5K - $5M',
      'Time in Business: 6+ months',
      'Monthly Revenue: At least $10,000',
      'Minimum Credit Score: 600',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 7,
    name: 'Credible',
    logo: '/images/table/Credible-logo.svg',
    totalScore: 9.0,
    trustpilotScore: 8.9,
    brandReputation: 9.1,
    popularityScore: 8.8,
    reviewCount: 5234,
    highlight: 'Compare personalized loan offers from multiple lenders',
    loanTypes: ['business_loan', 'sba'],
    minCreditScore: 'good',
    minRevenue: '20k_30k',
    minTimeInBusiness: '1_2',
    loanAmountRange: '50k_100k',
    details: [
      'Loan Amount: $5K - $500K',
      'Time in Business: 12+ months',
      'Annual Revenue: At least $100,000',
      'Minimum Credit Score: 650',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 8,
    name: 'LightStream',
    logo: '/images/table/LightStream-logo.svg',
    totalScore: 8.9,
    trustpilotScore: 9.3,
    brandReputation: 8.5,
    popularityScore: 8.7,
    reviewCount: 3124,
    highlight: 'Low rates for well-qualified borrowers with excellent credit',
    loanTypes: ['business_loan'],
    minCreditScore: 'excellent',
    minRevenue: 'more_30k',
    minTimeInBusiness: '2_plus',
    loanAmountRange: '100k_plus',
    details: [
      'Loan Amount: $5K - $100K',
      'Time in Business: 24+ months',
      'Annual Revenue: At least $200,000',
      'Minimum Credit Score: 720',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 9,
    name: 'Lending Club',
    logo: '/images/brands-logos/lending-cluc-logo.svg',
    totalScore: 8.8,
    trustpilotScore: 8.7,
    brandReputation: 8.9,
    popularityScore: 8.6,
    reviewCount: 2845,
    highlight: 'Peer-to-peer lending platform with competitive rates',
    loanTypes: ['business_loan', 'line_of_credit'],
    minCreditScore: 'good',
    minRevenue: '20k_30k',
    minTimeInBusiness: '1_2',
    loanAmountRange: '50k_100k',
    details: [
      'Loan Amount: $5K - $500K',
      'Time in Business: 12+ months',
      'Annual Revenue: At least $100,000',
      'Minimum Credit Score: 660',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 10,
    name: 'NerdWallet',
    logo: '/images/brands-logos/nerd-wallet-logo.svg',
    totalScore: 8.7,
    trustpilotScore: 8.5,
    brandReputation: 9.2,
    popularityScore: 8.4,
    reviewCount: 15678,
    highlight: 'Comprehensive comparison platform with expert financial advice',
    loanTypes: ['business_loan', 'sba', 'line_of_credit'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '50k_100k',
    details: [
      'Loan Amount: $5K - $500K',
      'Time in Business: 6+ months',
      'Monthly Revenue: At least $10,000',
      'Minimum Credit Score: 600',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
];
