// Lender data - easily swappable with real JSON data
export interface Lender {
  id: number;
  name: string;
  logo: string | null;
  totalScore: number;
  trustpilotScore: number | null;
  brandReputation: number | null;
  popularityScore: number | null;
  reviewCount: number | null;
  highlight: string;
  loanTypes: string[];
  minCreditScore: string;
  minRevenue: string;
  minTimeInBusiness: string;
  loanAmountRange: string;
  details: string[];
  ctaUrl: string;
  websiteUrl: string;
}

export const lendersData: Lender[] = [
  {
    id: 1,
    name: 'Biz2Credit',
    logo: '/images/brands-logos/Biz2credit-logo.svg',
    totalScore: 9.7,
    trustpilotScore: 9.4,
    brandReputation: 9.7,
    popularityScore: 9.6,
    reviewCount: 15146,
    highlight: 'Cash in the next 24hrs after approval',
    loanTypes: ['business_loan', 'working_capital', 'line_of_credit'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '50k_100k',
    details: [
      'Loan Amount: $25K - $6M',
      'Time in Business: 18+ months',
      'Average Monthly Revenue: At least $20,000',
      'Minimum Credit Score: 600',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 2,
    name: 'Lendzi',
    logo: null,
    totalScore: 9.4,
    trustpilotScore: 9.8,
    brandReputation: 9.1,
    popularityScore: 9.4,
    reviewCount: 1165,
    highlight: 'Top rated for ease & speed of funding process with personalized support',
    loanTypes: ['business_loan', 'working_capital'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '50k_100k',
    details: [
      'Loan Amount: $25K - $5M',
      'Time in Business: 18+ months',
      'Average Monthly Revenue: At least $20,000',
      'Minimum Credit Score: 600',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 3,
    name: 'OnDeck',
    logo: null,
    totalScore: 9.4,
    trustpilotScore: 9.0,
    brandReputation: 9.8,
    popularityScore: null,
    reviewCount: 4289,
    highlight: 'Trusted by Thousands of Small Businesses Nationwide',
    loanTypes: ['business_loan', 'line_of_credit'],
    minCreditScore: 'good',
    minRevenue: 'more_30k',
    minTimeInBusiness: '1_2',
    loanAmountRange: '100k_plus',
    details: [
      'Loan Amount: $5K - $250K',
      'Time in Business: 12+ months',
      'Annual Revenue: At least $100,000',
      'Minimum Credit Score: 625',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 4,
    name: 'SoFi',
    logo: '/images/table/Sofi-logo.svg',
    totalScore: 9.5,
    trustpilotScore: 8.6,
    brandReputation: 10,
    popularityScore: 10,
    reviewCount: 9665,
    highlight: 'Industry-leading digital banking experience with competitive rates',
    loanTypes: ['business_loan', 'sba'],
    minCreditScore: 'good',
    minRevenue: 'more_30k',
    minTimeInBusiness: '2_plus',
    loanAmountRange: '100k_plus',
    details: [
      'Loan Amount: $5K - $5M',
      'Time in Business: 24+ months',
      'Annual Revenue: At least $150,000',
      'Minimum Credit Score: 680',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 5,
    name: 'Fundbox',
    logo: null,
    totalScore: 9.2,
    trustpilotScore: 9.2,
    brandReputation: 8.8,
    popularityScore: 9.0,
    reviewCount: 3421,
    highlight: 'Fast approval with flexible credit lines for growing businesses',
    loanTypes: ['line_of_credit', 'working_capital'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '10k_50k',
    details: [
      'Credit Line: $1K - $150K',
      'Time in Business: 6+ months',
      'Annual Revenue: At least $50,000',
      'Minimum Credit Score: 600',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 6,
    name: 'BlueVine',
    logo: null,
    totalScore: 9.1,
    trustpilotScore: 8.8,
    brandReputation: 9.2,
    popularityScore: 8.9,
    reviewCount: 2847,
    highlight: 'Seamless line of credit with no monthly fees or prepayment penalties',
    loanTypes: ['line_of_credit', 'working_capital'],
    minCreditScore: 'good',
    minRevenue: '20k_30k',
    minTimeInBusiness: '1_2',
    loanAmountRange: '50k_100k',
    details: [
      'Credit Line: $5K - $250K',
      'Time in Business: 12+ months',
      'Monthly Revenue: At least $10,000',
      'Minimum Credit Score: 625',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 7,
    name: 'National Funding',
    logo: null,
    totalScore: 9.0,
    trustpilotScore: 9.0,
    brandReputation: 8.6,
    popularityScore: 8.8,
    reviewCount: 1523,
    highlight: 'Dedicated funding specialists for personalized loan solutions',
    loanTypes: ['business_loan', 'working_capital', 'other'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '50k_100k',
    details: [
      'Loan Amount: $5K - $500K',
      'Time in Business: 6+ months',
      'Monthly Revenue: At least $10,000',
      'Minimum Credit Score: 575',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 8,
    name: 'Credibly',
    logo: null,
    totalScore: 8.9,
    trustpilotScore: 8.7,
    brandReputation: 8.9,
    popularityScore: 8.6,
    reviewCount: 1876,
    highlight: 'Multiple financing options with fast 24-hour funding',
    loanTypes: ['business_loan', 'working_capital', 'line_of_credit'],
    minCreditScore: 'poor',
    minRevenue: 'less_10k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '10k_50k',
    details: [
      'Loan Amount: $5K - $400K',
      'Time in Business: 6+ months',
      'Monthly Revenue: At least $8,000',
      'Minimum Credit Score: 500',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 9,
    name: 'Kabbage (American Express)',
    logo: null,
    totalScore: 8.8,
    trustpilotScore: 8.2,
    brandReputation: 9.4,
    popularityScore: 8.5,
    reviewCount: 4521,
    highlight: 'Now backed by American Express with enhanced reliability',
    loanTypes: ['line_of_credit', 'working_capital'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '1_2',
    loanAmountRange: '50k_100k',
    details: [
      'Credit Line: $2K - $250K',
      'Time in Business: 12+ months',
      'Annual Revenue: At least $50,000',
      'Minimum Credit Score: 640',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 10,
    name: 'SmartBiz',
    logo: null,
    totalScore: 8.7,
    trustpilotScore: 9.1,
    brandReputation: 8.2,
    popularityScore: 8.3,
    reviewCount: 987,
    highlight: 'SBA loan specialists with competitive rates and expert guidance',
    loanTypes: ['sba', 'business_loan'],
    minCreditScore: 'good',
    minRevenue: 'more_30k',
    minTimeInBusiness: '2_plus',
    loanAmountRange: '100k_plus',
    details: [
      'Loan Amount: $30K - $5M',
      'Time in Business: 24+ months',
      'Annual Revenue: At least $100,000',
      'Minimum Credit Score: 675',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
];

