import type { Lender } from './lendersData';

export const lifeInsuranceData: Lender[] = [
  {
    id: 1,
    name: 'Haven Life',
    logo: null,
    ourScore: 9.7,
    trustpilotScore: 9.3,
    brandReputation: 9.6,
    popularityScore: 9.5,
    reviewCount: 14200,
    highlight: 'Best for term life insurance with instant approval',
    loanTypes: ['term'],
    minCreditScore: 'good',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '100k_500k',
    loanAmount: '$250K - $3M',
    goodDetails: [
      'Coverage: Term Life',
      'Instant Approval: Available',
      'No Medical Exam: For some',
      'Online Application: Yes',
    ],
    badDetails: [
      'Age Limit: 18-64',
      'Health Requirements: Varies',
      'Coverage Type: Term only',
      'Medical Exam: May be required',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 2,
    name: 'Policygenius',
    logo: null,
    ourScore: 9.6,
    trustpilotScore: 9.1,
    brandReputation: 9.5,
    popularityScore: 9.4,
    reviewCount: 16800,
    highlight: 'Compare quotes from top life insurance companies',
    loanTypes: ['term', 'whole'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '100k_500k',
    loanAmount: '$100K - $10M',
    goodDetails: [
      'Multiple Carriers: Yes',
      'Rate Comparison: Yes',
      'Expert Guidance: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Age Limit: 18-80',
      'Health Requirements: Varies',
      'Medical Exam: May be required',
      'Not a Direct Insurer: Marketplace',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 3,
    name: 'Bestow',
    logo: null,
    ourScore: 9.5,
    trustpilotScore: 9.2,
    brandReputation: 9.4,
    popularityScore: 9.3,
    reviewCount: 11200,
    highlight: 'No medical exam term life insurance',
    loanTypes: ['term'],
    minCreditScore: 'good',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '100k_500k',
    loanAmount: '$50K - $1.5M',
    goodDetails: [
      'Coverage: Term Life',
      'No Medical Exam: Yes',
      'Fast Approval: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Age Limit: 18-60',
      'Coverage Limit: $1.5M',
      'Health Questions: Required',
      'Coverage Type: Term only',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 4,
    name: 'Ladder',
    logo: null,
    ourScore: 9.4,
    trustpilotScore: 9.0,
    brandReputation: 9.3,
    popularityScore: 9.2,
    reviewCount: 9800,
    highlight: 'Flexible coverage you can adjust as needs change',
    loanTypes: ['term'],
    minCreditScore: 'good',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '100k_500k',
    loanAmount: '$100K - $8M',
    goodDetails: [
      'Coverage: Term Life',
      'Adjustable Coverage: Yes',
      'No Medical Exam: For some',
      'Online Application: Yes',
    ],
    badDetails: [
      'Age Limit: 18-60',
      'Health Requirements: Varies',
      'Medical Exam: May be required',
      'Coverage Type: Term only',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 5,
    name: 'State Farm',
    logo: null,
    ourScore: 9.3,
    trustpilotScore: 9.4,
    brandReputation: 9.7,
    popularityScore: 9.6,
    reviewCount: 24500,
    highlight: 'Trusted provider with comprehensive coverage options',
    loanTypes: ['term', 'whole', 'universal'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '500k_1m',
    loanAmount: '$50K - $10M',
    goodDetails: [
      'Coverage: All Types',
      'Local Agents: Available',
      'Multiple Plans: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Age Limit: 18-75',
      'Medical Exam: Usually required',
      'Health Requirements: Varies',
      'Premium: Higher than online',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 6,
    name: 'Northwestern Mutual',
    logo: null,
    ourScore: 9.2,
    trustpilotScore: 9.5,
    brandReputation: 9.8,
    popularityScore: 9.7,
    reviewCount: 18900,
    highlight: 'Best for whole life insurance and cash value',
    loanTypes: ['whole', 'universal'],
    minCreditScore: 'good',
    minRevenue: '20k_30k',
    minTimeInBusiness: '1_2',
    loanAmountRange: '500k_1m',
    loanAmount: '$100K - $10M',
    goodDetails: [
      'Coverage: Whole/Universal',
      'Cash Value: Yes',
      'Dividends: Available',
      'Financial Planning: Yes',
    ],
    badDetails: [
      'Age Limit: 18-75',
      'Medical Exam: Required',
      'Premium: Higher cost',
      'Minimum Coverage: $100K',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 7,
    name: 'New York Life',
    logo: null,
    ourScore: 9.1,
    trustpilotScore: 9.3,
    brandReputation: 9.7,
    popularityScore: 9.5,
    reviewCount: 16200,
    highlight: 'Established provider with strong financial ratings',
    loanTypes: ['term', 'whole', 'universal'],
    minCreditScore: 'good',
    minRevenue: '20k_30k',
    minTimeInBusiness: '1_2',
    loanAmountRange: '500k_1m',
    loanAmount: '$100K - $10M',
    goodDetails: [
      'Coverage: All Types',
      'Financial Strength: A++',
      'Multiple Plans: Yes',
      'Agents: Available',
    ],
    badDetails: [
      'Age Limit: 18-75',
      'Medical Exam: Usually required',
      'Premium: Higher cost',
      'Minimum Coverage: $100K',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 8,
    name: 'MassMutual',
    logo: null,
    ourScore: 9.0,
    trustpilotScore: 9.2,
    brandReputation: 9.6,
    popularityScore: 9.4,
    reviewCount: 13800,
    highlight: 'Best for whole life with dividend payments',
    loanTypes: ['whole', 'universal'],
    minCreditScore: 'good',
    minRevenue: '20k_30k',
    minTimeInBusiness: '1_2',
    loanAmountRange: '500k_1m',
    loanAmount: '$100K - $10M',
    goodDetails: [
      'Coverage: Whole/Universal',
      'Dividends: Yes',
      'Cash Value: Yes',
      'Financial Strength: A++',
    ],
    badDetails: [
      'Age Limit: 18-75',
      'Medical Exam: Required',
      'Premium: Higher cost',
      'Minimum Coverage: $100K',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
];
