import type { Lender } from './lendersData';

export const mortgageLoansData: Lender[] = [
  {
    id: 1,
    name: 'SoFi',
    logo: '/images/table/Sofi-logo.svg',
    ourScore: 9.7,
    trustpilotScore: 9.2,
    brandReputation: 9.8,
    popularityScore: 9.6,
    reviewCount: 12500,
    highlight: 'Competitive rates and fast pre-approval process',
    loanTypes: ['conventional'],
    minCreditScore: 'good',
    minRevenue: '20k_30k',
    minTimeInBusiness: '1_2',
    loanAmountRange: '400k_750k',
    loanAmount: '$100K - $5M',
    goodDetails: [
      'Rate Range: 2.99% - 6.99%',
      'No PMI Required: With 20% down',
      'Fast Pre-approval: 24 hours',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 680',
      'Down Payment: 10-20%',
      'Debt-to-Income Ratio: Under 43%',
      'Closing Time: 30-45 days',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 2,
    name: 'LendingTree',
    logo: '/images/table/LendingTree-logo.svg',
    ourScore: 9.6,
    trustpilotScore: 9.1,
    brandReputation: 9.5,
    popularityScore: 9.3,
    reviewCount: 15200,
    highlight: 'Compare mortgage rates from multiple lenders',
    loanTypes: ['conventional', 'fha', 'va'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '200k_400k',
    loanAmount: '$50K - $2M',
    goodDetails: [
      'Multiple Offers: Yes',
      'All Loan Types: Available',
      'Rate Comparison: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 620',
      'Down Payment: 3-20%',
      'APR Range: 2.5% - 7.5%',
      'Closing Time: 30-60 days',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 3,
    name: 'NerdWallet',
    logo: '/images/brands-logos/nerd-wallet-logo.svg',
    ourScore: 9.5,
    trustpilotScore: 8.8,
    brandReputation: 9.6,
    popularityScore: 9.5,
    reviewCount: 18500,
    highlight: 'Expert guidance to find the best mortgage rates',
    loanTypes: ['conventional', 'fha', 'va', 'usda'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '200k_400k',
    loanAmount: '$50K - $3M',
    goodDetails: [
      'Expert Reviews: Yes',
      'Mortgage Calculator: Yes',
      'Educational Resources: Yes',
      'Free Service: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 620',
      'Down Payment: 3-20%',
      'Not a Direct Lender: Marketplace',
      'Closing Time: Varies by lender',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 4,
    name: 'Credible',
    logo: '/images/table/Credible-logo.svg',
    ourScore: 9.4,
    trustpilotScore: 9.0,
    brandReputation: 9.4,
    popularityScore: 9.2,
    reviewCount: 11200,
    highlight: 'Compare prequalified mortgage rates without hard credit pull',
    loanTypes: ['conventional', 'fha'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '200k_400k',
    loanAmount: '$50K - $2M',
    goodDetails: [
      'Prequalification: No hard pull',
      'Rate Comparison: Yes',
      'No Fees: From Credible',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 620',
      'Down Payment: 3-20%',
      'APR Range: 2.5% - 7.5%',
      'Closing Time: 30-45 days',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 5,
    name: 'LightStream',
    logo: '/images/table/LightStream-logo.svg',
    ourScore: 9.3,
    trustpilotScore: 9.4,
    brandReputation: 9.6,
    popularityScore: 9.4,
    reviewCount: 9800,
    highlight: 'Best for jumbo loans and high-value properties',
    loanTypes: ['conventional'],
    minCreditScore: 'excellent',
    minRevenue: 'more_30k',
    minTimeInBusiness: '2_plus',
    loanAmountRange: '750k_plus',
    loanAmount: '$200K - $5M',
    goodDetails: [
      'Rate Range: 2.75% - 6.5%',
      'Jumbo Loans: Available',
      'No PMI: With 20% down',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 720',
      'Down Payment: 20%+',
      'Income Requirement: $100,000+',
      'Closing Time: 30-45 days',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 6,
    name: 'Fundera',
    logo: '/images/brands-logos/fundera-logo.svg',
    ourScore: 9.2,
    trustpilotScore: 9.0,
    brandReputation: 9.2,
    popularityScore: 9.0,
    reviewCount: 8400,
    highlight: 'Expert guidance to find the best mortgage for your situation',
    loanTypes: ['conventional', 'fha', 'va'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '200k_400k',
    loanAmount: '$50K - $2M',
    goodDetails: [
      'Expert Guidance: Yes',
      'Multiple Loan Types: Yes',
      'Rate Comparison: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 620',
      'Down Payment: 3-20%',
      'APR Range: 2.5% - 7.5%',
      'Closing Time: 30-60 days',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 7,
    name: 'Lendio',
    logo: '/images/brands-logos/lendio-logo.svg',
    ourScore: 9.1,
    trustpilotScore: 8.6,
    brandReputation: 9.0,
    popularityScore: 8.8,
    reviewCount: 9200,
    highlight: 'Access to multiple mortgage lenders with one application',
    loanTypes: ['conventional', 'fha'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '200k_400k',
    loanAmount: '$50K - $1.5M',
    goodDetails: [
      'Multiple Lenders: Yes',
      'One Application: Yes',
      'Fast Matching: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 620',
      'Down Payment: 3-20%',
      'APR Range: 2.5% - 7.5%',
      'Closing Time: 30-60 days',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 8,
    name: 'Biz2Credit',
    logo: '/images/brands-logos/Biz2credit-logo.svg',
    ourScore: 9.0,
    trustpilotScore: 9.4,
    brandReputation: 9.7,
    popularityScore: 9.6,
    reviewCount: 15146,
    highlight: 'Fast mortgage pre-approval and competitive rates',
    loanTypes: ['conventional', 'fha'],
    minCreditScore: 'good',
    minRevenue: '20k_30k',
    minTimeInBusiness: '1_2',
    loanAmountRange: '400k_750k',
    loanAmount: '$100K - $2M',
    goodDetails: [
      'Fast Pre-approval: 24 hours',
      'Competitive Rates: Yes',
      'No PMI: With 20% down',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 650',
      'Down Payment: 10-20%',
      'Debt-to-Income Ratio: Under 43%',
      'Closing Time: 30-45 days',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
];
