import type { Lender } from './lendersData';

export const onlineBankingData: Lender[] = [
  {
    id: 1,
    name: 'SoFi',
    logo: '/images/table/Sofi-logo.svg',
    ourScore: 9.7,
    trustpilotScore: 9.2,
    brandReputation: 9.8,
    popularityScore: 9.6,
    reviewCount: 12500,
    highlight: 'Best overall online banking with high APY and no fees',
    loanTypes: ['checking', 'savings', 'high_yield'],
    minCreditScore: 'good',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '0',
    loanAmount: '4.60% APY',
    goodDetails: [
      'APY: 4.60%',
      'No Monthly Fees: Yes',
      'No Minimum Balance: Yes',
      'Mobile App: Yes',
    ],
    badDetails: [
      'ATM Fees: Reimbursed up to $50',
      'Physical Branches: None',
      'Cash Deposits: Limited',
      'FDIC Insured: Yes',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 2,
    name: 'Ally Bank',
    logo: null,
    ourScore: 9.6,
    trustpilotScore: 9.1,
    brandReputation: 9.6,
    popularityScore: 9.5,
    reviewCount: 18500,
    highlight: 'High-yield savings with no minimum balance requirements',
    loanTypes: ['savings', 'high_yield', 'money_market'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '0',
    loanAmount: '4.35% APY',
    goodDetails: [
      'APY: 4.35%',
      'No Monthly Fees: Yes',
      'No Minimum Balance: Yes',
      'Mobile App: Yes',
    ],
    badDetails: [
      'ATM Access: Allpoint network',
      'Physical Branches: None',
      'Cash Deposits: Not available',
      'FDIC Insured: Yes',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 3,
    name: 'Marcus by Goldman Sachs',
    logo: null,
    ourScore: 9.5,
    trustpilotScore: 9.0,
    brandReputation: 9.7,
    popularityScore: 9.4,
    reviewCount: 15200,
    highlight: 'High-yield savings from a trusted financial institution',
    loanTypes: ['savings', 'high_yield'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '0',
    loanAmount: '4.40% APY',
    goodDetails: [
      'APY: 4.40%',
      'No Monthly Fees: Yes',
      'No Minimum Balance: Yes',
      'Mobile App: Yes',
    ],
    badDetails: [
      'ATM Access: Limited',
      'Physical Branches: None',
      'Cash Deposits: Not available',
      'FDIC Insured: Yes',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 4,
    name: 'Capital One 360',
    logo: null,
    ourScore: 9.4,
    trustpilotScore: 8.9,
    brandReputation: 9.5,
    popularityScore: 9.3,
    reviewCount: 16800,
    highlight: 'Best for checking and savings combo with branch access',
    loanTypes: ['checking', 'savings', 'high_yield'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '0',
    loanAmount: '4.25% APY',
    goodDetails: [
      'APY: 4.25%',
      'No Monthly Fees: Yes',
      'Branch Access: Available',
      'Mobile App: Yes',
    ],
    badDetails: [
      'Minimum Balance: $0',
      'ATM Fees: Reimbursed at select ATMs',
      'Cash Deposits: At branches',
      'FDIC Insured: Yes',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 5,
    name: 'Discover Bank',
    logo: null,
    ourScore: 9.3,
    trustpilotScore: 9.2,
    brandReputation: 9.4,
    popularityScore: 9.2,
    reviewCount: 14200,
    highlight: 'High-yield savings with cashback checking',
    loanTypes: ['checking', 'savings', 'high_yield'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '0',
    loanAmount: '4.30% APY',
    goodDetails: [
      'APY: 4.30%',
      'No Monthly Fees: Yes',
      'Cashback Checking: Yes',
      'Mobile App: Yes',
    ],
    badDetails: [
      'ATM Access: 60,000+ ATMs',
      'Physical Branches: None',
      'Cash Deposits: Limited',
      'FDIC Insured: Yes',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 6,
    name: 'American Express',
    logo: null,
    ourScore: 9.2,
    trustpilotScore: 9.1,
    brandReputation: 9.6,
    popularityScore: 9.5,
    reviewCount: 18900,
    highlight: 'High-yield savings from a trusted brand',
    loanTypes: ['savings', 'high_yield'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '0',
    loanAmount: '4.35% APY',
    goodDetails: [
      'APY: 4.35%',
      'No Monthly Fees: Yes',
      'No Minimum Balance: Yes',
      'Mobile App: Yes',
    ],
    badDetails: [
      'ATM Access: Limited',
      'Physical Branches: None',
      'Cash Deposits: Not available',
      'FDIC Insured: Yes',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 7,
    name: 'CIT Bank',
    logo: null,
    ourScore: 9.1,
    trustpilotScore: 8.8,
    brandReputation: 9.2,
    popularityScore: 9.0,
    reviewCount: 11200,
    highlight: 'Competitive rates on savings and money market accounts',
    loanTypes: ['savings', 'high_yield', 'money_market'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '100_1000',
    loanAmount: '4.50% APY',
    goodDetails: [
      'APY: 4.50%',
      'No Monthly Fees: Yes',
      'High Rates: Yes',
      'Mobile App: Yes',
    ],
    badDetails: [
      'Minimum Balance: $100-$1,000',
      'ATM Access: Limited',
      'Physical Branches: None',
      'FDIC Insured: Yes',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 8,
    name: 'Synchrony Bank',
    logo: null,
    ourScore: 9.0,
    trustpilotScore: 8.7,
    brandReputation: 9.1,
    popularityScore: 8.9,
    reviewCount: 9800,
    highlight: 'High-yield savings with no minimum balance',
    loanTypes: ['savings', 'high_yield'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    loanAmountRange: '0',
    loanAmount: '4.25% APY',
    goodDetails: [
      'APY: 4.25%',
      'No Monthly Fees: Yes',
      'No Minimum Balance: Yes',
      'Mobile App: Yes',
    ],
    badDetails: [
      'ATM Access: Limited',
      'Physical Branches: None',
      'Cash Deposits: Not available',
      'FDIC Insured: Yes',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
];
