import type { Brand } from './lendersData';

export const personalLoansData: Brand[] = [
  {
    id: 1,
    name: 'SoFi',
    logo: '/images/table/Sofi-logo.svg',
    ourScore: 9.7,
    trustpilotScore: 9.2,
    brandReputation: 9.8,
    popularityScore: 9.6,
    reviewCount: 12500,
    highlight: 'Low rates and no fees for well-qualified borrowers',
    productTypes: ['personal_loan'],
    minCreditScore: 'good',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '5k_25k',
    amount: '$5K - $100K',
    goodDetails: [
      'APR Range: 5.99% - 23.43%',
      'No Origination Fee: Yes',
      'Unemployment Protection: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 680',
      'Income Requirement: $45,000+',
      'Debt-to-Income Ratio: Under 50%',
      'Funding Speed: 1-3 business days',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 2,
    name: 'LightStream',
    logo: '/images/table/LightStream-logo.svg',
    ourScore: 9.6,
    trustpilotScore: 9.4,
    brandReputation: 9.6,
    popularityScore: 9.4,
    reviewCount: 9800,
    highlight: 'Best for borrowers with excellent credit seeking low rates',
    productTypes: ['personal_loan'],
    minCreditScore: 'excellent',
    minRevenue: '20k_30k',
    minTimeInBusiness: '6m_1y',
    amountRange: '5k_25k',
    amount: '$5K - $100K',
    goodDetails: [
      'APR Range: 4.99% - 19.99%',
      'No Fees: Yes',
      'Same-Day Funding: Available',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 720',
      'Income Requirement: $50,000+',
      'Debt-to-Income Ratio: Under 40%',
      'Co-signers: Not allowed',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 3,
    name: 'LendingTree',
    logo: '/images/table/LendingTree-logo.svg',
    ourScore: 9.5,
    trustpilotScore: 9.1,
    brandReputation: 9.5,
    popularityScore: 9.3,
    reviewCount: 15200,
    highlight: 'Compare multiple offers from top lenders in one place',
    productTypes: ['personal_loan'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: 'under_5k',
    amount: '$1K - $50K',
    goodDetails: [
      'Multiple Offers: Yes',
      'Soft Credit Check: Initial',
      'Fast Comparison: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 600',
      'APR Range: 5.99% - 35.99%',
      'Origination Fee: Varies by lender',
      'Funding Speed: 1-7 business days',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 4,
    name: 'Credible',
    logo: '/images/table/Credible-logo.svg',
    ourScore: 9.4,
    trustpilotScore: 9.0,
    brandReputation: 9.4,
    popularityScore: 9.2,
    reviewCount: 11200,
    highlight: 'Compare prequalified rates without affecting your credit',
    productTypes: ['personal_loan'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '5k_25k',
    amount: '$1K - $100K',
    goodDetails: [
      'Prequalification: No hard pull',
      'Multiple Lenders: Yes',
      'No Fees: From Credible',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 600',
      'APR Range: 5.99% - 35.99%',
      'Income Requirement: Varies',
      'Funding Speed: 1-5 business days',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 5,
    name: 'NerdWallet',
    logo: '/images/brands-logos/nerd-wallet-logo.svg',
    ourScore: 9.3,
    trustpilotScore: 8.8,
    brandReputation: 9.6,
    popularityScore: 9.5,
    reviewCount: 18500,
    highlight: 'Expert guidance to find the best personal loan for you',
    productTypes: ['personal_loan'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: 'under_5k',
    amount: '$1K - $50K',
    goodDetails: [
      'Expert Reviews: Yes',
      'Comparison Tools: Yes',
      'Educational Resources: Yes',
      'Free Service: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 600',
      'APR Range: Varies by lender',
      'Not a Direct Lender: Marketplace',
      'Funding Speed: Varies by lender',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 6,
    name: 'Credit Ninja',
    logo: '/images/brands-logos/credit-ninja.svg',
    ourScore: 9.2,
    trustpilotScore: 8.9,
    brandReputation: 9.2,
    popularityScore: 9.0,
    reviewCount: 7500,
    highlight: 'Fast approval for borrowers with fair credit',
    productTypes: ['personal_loan'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: 'under_5k',
    amount: '$500 - $5K',
    goodDetails: [
      'Fast Approval: Same day',
      'Fair Credit Accepted: Yes',
      'Online Application: Yes',
      'Flexible Terms: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 580',
      'APR Range: 9.99% - 35.99%',
      'Origination Fee: Up to 5%',
      'Maximum Loan: $5,000',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 7,
    name: 'FundBox',
    logo: '/images/brands-logos/fund-box.svg',
    ourScore: 9.1,
    trustpilotScore: 8.7,
    brandReputation: 9.1,
    popularityScore: 8.9,
    reviewCount: 6400,
    highlight: 'Quick access to funds for personal expenses',
    productTypes: ['personal_loan'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: 'under_5k',
    amount: '$1K - $10K',
    goodDetails: [
      'Fast Funding: 24-48 hours',
      'Simple Application: Yes',
      'No Collateral: Required',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 600',
      'APR Range: 10% - 30%',
      'Origination Fee: 1-5%',
      'Maximum Loan: $10,000',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 8,
    name: 'Lendio',
    logo: '/images/brands-logos/lendio-logo.svg',
    ourScore: 9.0,
    trustpilotScore: 8.6,
    brandReputation: 9.0,
    popularityScore: 8.8,
    reviewCount: 9200,
    highlight: 'Access to 75+ lenders with one simple application',
    productTypes: ['personal_loan'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '5k_25k',
    amount: '$1K - $100K',
    goodDetails: [
      'Multiple Lenders: 75+',
      'One Application: Yes',
      'Fast Matching: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 600',
      'APR Range: 5.99% - 35.99%',
      'Origination Fee: Varies',
      'Funding Speed: 1-7 business days',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
];
