import type { Brand } from './lendersData';

export const petInsuranceData: Brand[] = [
  {
    id: 1,
    name: 'Healthy Paws',
    logo: null,
    ourScore: 9.7,
    trustpilotScore: 9.5,
    brandReputation: 9.6,
    popularityScore: 9.5,
    reviewCount: 18500,
    highlight: 'Best overall pet insurance with comprehensive coverage',
    productTypes: ['pet_insurance'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: 'under_10k',
    amount: '$20 - $100/month',
    goodDetails: [
      'Coverage: Accident & Illness',
      'Reimbursement: 70-90%',
      'No Annual Limit: Yes',
      'Online Claims: Yes',
    ],
    badDetails: [
      'Deductible: $100-$500',
      'Waiting Period: 15 days',
      'Pre-existing Conditions: Excluded',
      'Age Limit: Varies by breed',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 2,
    name: 'ASPCA Pet Insurance',
    logo: null,
    ourScore: 9.6,
    trustpilotScore: 9.3,
    brandReputation: 9.7,
    popularityScore: 9.4,
    reviewCount: 15200,
    highlight: 'Trusted name with flexible coverage options',
    productTypes: ['pet_insurance'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: 'under_10k',
    amount: '$25 - $120/month',
    goodDetails: [
      'Coverage: Comprehensive',
      'Reimbursement: 70-90%',
      'Multiple Plans: Yes',
      'Online Claims: Yes',
    ],
    badDetails: [
      'Deductible: $100-$500',
      'Waiting Period: 14 days',
      'Pre-existing Conditions: Excluded',
      'Annual Limit: Varies by plan',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 3,
    name: 'Embrace Pet Insurance',
    logo: null,
    ourScore: 9.5,
    trustpilotScore: 9.2,
    brandReputation: 9.5,
    popularityScore: 9.3,
    reviewCount: 12800,
    highlight: 'Best for customizable coverage and wellness plans',
    productTypes: ['pet_insurance'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: 'under_10k',
    amount: '$30 - $150/month',
    goodDetails: [
      'Coverage: Customizable',
      'Wellness Plans: Available',
      'Reimbursement: 70-90%',
      'Online Claims: Yes',
    ],
    badDetails: [
      'Deductible: $200-$1,000',
      'Waiting Period: 14 days',
      'Pre-existing Conditions: Excluded',
      'Annual Limit: Up to $30,000',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 4,
    name: 'Petplan',
    logo: null,
    ourScore: 9.4,
    trustpilotScore: 9.1,
    brandReputation: 9.4,
    popularityScore: 9.2,
    reviewCount: 11200,
    highlight: 'Comprehensive coverage with no upper age limit',
    productTypes: ['pet_insurance'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: 'under_10k',
    amount: '$25 - $110/month',
    goodDetails: [
      'Coverage: Comprehensive',
      'No Age Limit: Yes',
      'Reimbursement: 70-90%',
      'Online Claims: Yes',
    ],
    badDetails: [
      'Deductible: $100-$500',
      'Waiting Period: 14 days',
      'Pre-existing Conditions: Excluded',
      'Annual Limit: Up to $25,000',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 5,
    name: 'Trupanion',
    logo: null,
    ourScore: 9.3,
    trustpilotScore: 9.4,
    brandReputation: 9.3,
    popularityScore: 9.1,
    reviewCount: 9800,
    highlight: 'Best for lifetime coverage with no payout limits',
    productTypes: ['pet_insurance'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: 'under_10k',
    amount: '$30 - $140/month',
    goodDetails: [
      'Coverage: Lifetime',
      'No Payout Limit: Yes',
      'Direct Vet Payment: Available',
      'Online Claims: Yes',
    ],
    badDetails: [
      'Deductible: $0-$1,000',
      'Waiting Period: 30 days',
      'Pre-existing Conditions: Excluded',
      'Reimbursement: 90% only',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 6,
    name: 'Nationwide Pet Insurance',
    logo: null,
    ourScore: 9.2,
    trustpilotScore: 9.0,
    brandReputation: 9.5,
    popularityScore: 9.4,
    reviewCount: 14500,
    highlight: 'Trusted insurance provider with multiple plan options',
    productTypes: ['pet_insurance'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: 'under_10k',
    amount: '$35 - $160/month',
    goodDetails: [
      'Coverage: Multiple Plans',
      'Wellness Plans: Available',
      'Reimbursement: 70-90%',
      'Online Claims: Yes',
    ],
    badDetails: [
      'Deductible: $100-$500',
      'Waiting Period: 14 days',
      'Pre-existing Conditions: Excluded',
      'Annual Limit: Varies by plan',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 7,
    name: 'Lemonade Pet Insurance',
    logo: null,
    ourScore: 9.1,
    trustpilotScore: 8.9,
    brandReputation: 9.2,
    popularityScore: 9.0,
    reviewCount: 8700,
    highlight: 'Modern digital experience with fast claims processing',
    productTypes: ['pet_insurance'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: 'under_10k',
    amount: '$20 - $90/month',
    goodDetails: [
      'Coverage: Comprehensive',
      'Fast Claims: Yes',
      'Mobile App: Yes',
      'Online Claims: Yes',
    ],
    badDetails: [
      'Deductible: $100-$500',
      'Waiting Period: 14 days',
      'Pre-existing Conditions: Excluded',
      'Annual Limit: Up to $100,000',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 8,
    name: 'Pets Best',
    logo: null,
    ourScore: 9.0,
    trustpilotScore: 8.8,
    brandReputation: 9.1,
    popularityScore: 8.9,
    reviewCount: 10200,
    highlight: 'Affordable coverage with flexible deductible options',
    productTypes: ['pet_insurance'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: 'under_10k',
    amount: '$20 - $100/month',
    goodDetails: [
      'Coverage: Comprehensive',
      'Flexible Deductibles: Yes',
      'Reimbursement: 70-90%',
      'Online Claims: Yes',
    ],
    badDetails: [
      'Deductible: $50-$1,000',
      'Waiting Period: 14 days',
      'Pre-existing Conditions: Excluded',
      'Annual Limit: Up to $5,000',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
];
