import type { Brand } from './lendersData';

export const petInsuranceData: Brand[] = [
  {
    id: 1,
    name: 'Healthy Paws',
    logo: null,
    ourScore: 9.5,
    trustpilotScore: null,
    brandReputation: 9.4,
    popularityScore: 9.0,
    reviewCount: null,
    highlight:
      'Top-rated pet insurer offering a single comprehensive plan with no annual or lifetime coverage limits and fast claim reimbursements.',
    productTypes: ['pet_insurance'],
    amount: '$20 - $100/month',
    amountRange: 'under_10k',
    goodDetails: [
      'Unlimited coverage – no caps on payouts per year or per condition',
      'Covers new accidents and illnesses, hereditary and congenital conditions',
      'Claims processed quickly (often within 2 days) via mobile app',
      'Online Application: Yes',
    ],
    badDetails: [
      'Does not cover routine care or wellness visits (accident/illness only)',
      'No option to add exam fee coverage or wellness riders',
      'Premiums increase as pet ages, and no new enrollments for pets 14+ years old',
      'Waiting Period: 15 days',
    ],
    ctaUrl: 'https://www.healthypaws.com',
    websiteUrl: 'https://www.healthypaws.com',
  },
  {
    id: 2,
    name: 'Trupanion',
    logo: null,
    ourScore: 9.3,
    trustpilotScore: null,
    brandReputation: 9.1,
    popularityScore: 8.7,
    reviewCount: null,
    highlight:
      'Premium pet insurance known for 90% reimbursement of actual vet bills, unlimited lifetime coverage, and an option for direct vet payments.',
    productTypes: ['pet_insurance'],
    amount: '$30 - $120/month',
    amountRange: 'under_10k',
    goodDetails: [
      '90% reimbursement on eligible vet bills with no payout limits',
      'Lifetime per-condition deductible (you pay once per condition, not per year)',
      'Optional direct pay to vets so you only pay your portion at checkout',
      'Online Application: Yes',
    ],
    badDetails: [
      'Monthly premiums tend to be higher than many competitors',
      'Does not cover routine wellness care by default (accident & illness only)',
      'Exam fees and taxes not covered unless added via Recovery and Complementary Care rider',
      'Waiting Period: 5 days',
    ],
    ctaUrl: 'https://www.trupanion.com',
    websiteUrl: 'https://www.trupanion.com',
  },
  {
    id: 3,
    name: 'Embrace',
    logo: null,
    ourScore: 9.2,
    trustpilotScore: null,
    brandReputation: 9.0,
    popularityScore: 8.5,
    reviewCount: null,
    highlight:
      'Flexible pet insurance with adjustable deductibles and a diminishing deductible feature, plus optional Wellness Rewards for routine care.',
    productTypes: ['pet_insurance'],
    amount: '$15 - $80/month',
    amountRange: 'under_10k',
    goodDetails: [
      "Deductible automatically decreases $50 each year you don't receive a claim reimbursement (Healthy Pet Deductible)",
      'Offers optional Wellness Rewards add-on to cover routine care like vaccines and dental cleaning',
      'Covers curable pre-existing conditions after 12-month symptom-free period',
      'Online Application: Yes',
    ],
    badDetails: [
      'New enrollments for pets age 15 or older only eligible for accident-only coverage',
      "Wellness Rewards is a savings plan (not insurance) and unused funds don't roll over year to year",
      'Annual coverage limits apply (no unlimited option on standard plans)',
      'Waiting Period: 14 days',
    ],
    ctaUrl: 'https://www.embracepetinsurance.com',
    websiteUrl: 'https://www.embracepetinsurance.com',
  },
  {
    id: 4,
    name: 'Fetch by The Dodo (Petplan)',
    logo: null,
    ourScore: 9.0,
    trustpilotScore: null,
    brandReputation: 8.8,
    popularityScore: 8.0,
    reviewCount: null,
    highlight:
      'Comprehensive pet insurance (formerly Petplan) covering a wide range of conditions – even hereditary issues and dental injuries – with no upper age limit for enrollment.',
    productTypes: ['pet_insurance'],
    amount: '$20 - $100/month',
    amountRange: 'under_10k',
    goodDetails: [
      'Covers dental injuries and diseases (up to full-mouth treatment) as part of standard coverage',
      'No maximum age limit – older pets can be enrolled (though premiums will reflect age)',
      'Offers holistic care coverage (acupuncture, hydrotherapy, etc.) if recommended by a vet',
      'Online Application: Yes',
    ],
    badDetails: [
      'Does not offer a preventative care/wellness add-on option',
      '14-day waiting period for illnesses (and 6 months for cruciate/ligament issues) which is longer than some competitors',
      'Premiums can be on the higher side, especially for older pets or certain breeds',
      'Waiting Period: 14 days',
    ],
    ctaUrl: 'https://www.fetchpet.com',
    websiteUrl: 'https://www.fetchpet.com',
  },
  {
    id: 5,
    name: 'Spot Pet Insurance',
    logo: null,
    ourScore: 8.9,
    trustpilotScore: null,
    brandReputation: 8.7,
    popularityScore: 7.8,
    reviewCount: null,
    highlight:
      'Highly customizable pet insurance (backed by Cesar Millan) allowing 70%, 80%, or 90% reimbursement and multiple annual limit options, plus optional wellness coverage.',
    productTypes: ['pet_insurance'],
    amount: '$20 - $100/month',
    amountRange: 'under_10k',
    goodDetails: [
      'Choose reimbursement rate (70%, 80%, 90%) and annual limits from $2,500 up to unlimited',
      'Covers microchip implantation and exam fees by default (many insurers exclude exam fees)',
      'Optional preventive care plans available (Gold and Platinum) to cover routine vet visits, shots, etc.',
      'Online Application: Yes',
    ],
    badDetails: [
      'Higher reimbursement and unlimited plans can get very expensive in monthly premium',
      '14-day waiting period for accidents (some competitors have shorter accident waiting times like 2-3 days)',
      'Some customer complaints about slow claims processing times',
      'Waiting Period: 14 days',
    ],
    ctaUrl: 'https://www.spotpetins.com',
    websiteUrl: 'https://www.spotpetins.com',
  },
  {
    id: 6,
    name: 'ASPCA Pet Health Insurance',
    logo: null,
    ourScore: 8.8,
    trustpilotScore: null,
    brandReputation: 9.0,
    popularityScore: 9.2,
    reviewCount: null,
    highlight:
      'Pet insurance program affiliated with the ASPCA, offering accident/illness plans and optional wellness coverage for cats, dogs, and even horses.',
    productTypes: ['pet_insurance'],
    amount: '$25 - $120/month',
    amountRange: 'under_10k',
    goodDetails: [
      'Covers horses in addition to dogs and cats (uncommon among pet insurers)',
      '10% multi-pet discount for each additional pet policy',
      'Option to add preventive care coverage for routine exams, vaccines, and dental cleanings',
      'Online Application: Yes',
    ],
    badDetails: [
      'Annual payout limits per year (no unlimited option unless choosing the highest tier at higher cost)',
      'Routine care not covered without adding a wellness rider',
      'Like many insurers, has a 14-day waiting period for illnesses and accidents',
      'Waiting Period: 14 days',
    ],
    ctaUrl: 'https://www.aspcapetinsurance.com',
    websiteUrl: 'https://www.aspcapetinsurance.com',
  },
  {
    id: 7,
    name: 'Lemonade Pet Insurance',
    logo: null,
    ourScore: 9.0,
    trustpilotScore: null,
    brandReputation: 8.9,
    popularityScore: 8.8,
    reviewCount: null,
    highlight:
      'Tech-focused insurer with a seamless app – offers customizable pet health insurance with fast claim payments and discounts for bundling with home/renters insurance.',
    productTypes: ['pet_insurance'],
    amount: '$20 - $100/month',
    amountRange: 'under_10k',
    goodDetails: [
      'Very quick claims processing, often instantly for certain claims via AI in the mobile app',
      'Discounts available for bundling with Lemonade home or renters insurance (up to 10%) and for multiple pets (5%)',
      'Preventive care packages available (puppy/kitten and adult pet) to cover routine exams, vaccines, and wellness',
      'Online Application: Yes',
    ],
    badDetails: [
      'Not yet available in all states (rollout of coverage is ongoing)',
      'Limited live customer support by phone – heavily app/internet based service',
      'Annual coverage limit options max out at $100k (no unlimited option yet)',
      'Waiting Period: 14 days',
    ],
    ctaUrl: 'https://www.lemonade.com/pet',
    websiteUrl: 'https://www.lemonade.com',
  },
  {
    id: 8,
    name: 'Nationwide Pet Insurance',
    logo: null,
    ourScore: 8.7,
    trustpilotScore: null,
    brandReputation: 9.2,
    popularityScore: 9.5,
    reviewCount: null,
    highlight:
      'Established insurer (formerly VPI) offering pet insurance for a wide range of animals – including dogs, cats, birds, and exotic pets – with the option of avian & exotic coverage.',
    productTypes: ['pet_insurance'],
    amount: '$30 - $150/month',
    amountRange: 'under_10k',
    goodDetails: [
      'Only major insurer that covers exotic pets and birds in addition to cats and dogs',
      'Offers a comprehensive Avian & Exotic Pet Plan uniquely designed for those animals',
      'Whole Pet with Wellness plan available, covering 90% of nearly all vet and routine expenses',
      'Online Application: Yes',
    ],
    badDetails: [
      'Whole Pet plan has an annual cap ($10k) and can be pricey; other plans have defined benefit schedules with caps per condition',
      'Older pets (over 10) may only qualify for limited coverage or have higher premiums',
      'Claims can require paper forms and have slower reimbursement times compared to newer tech-driven companies',
      'Waiting Period: 14 days',
    ],
    ctaUrl: 'https://www.petinsurance.com',
    websiteUrl: 'https://www.petinsurance.com',
  },
  {
    id: 9,
    name: 'Pets Best',
    logo: null,
    ourScore: 9.1,
    trustpilotScore: null,
    brandReputation: 9.0,
    popularityScore: 8.3,
    reviewCount: null,
    highlight:
      'Popular pet insurer offering optional unlimited annual coverage, direct vet payment, and a variety of add-on wellness plans to cover routine pet care needs.',
    productTypes: ['pet_insurance'],
    amount: '$20 - $100/month',
    amountRange: 'under_10k',
    goodDetails: [
      'Offers an unlimited annual benefit option for full peace of mind coverage',
      'Has direct veterinary reimbursement option so vets can be paid directly on approved claims',
      'Multiple wellness add-on tiers available for routine care like vaccines, spay/neuter, and dental cleaning',
      'Online Application: Yes',
    ],
    badDetails: [
      '6-month waiting period for cruciate ligament and related conditions (unless waived by vet exam)',
      'Charges a $2 transaction fee if not enrolling in direct pay (ACH) for premiums',
      "Doesn't cover exam fees in standard accident/illness plan (exam fee coverage is an extra add-on)",
      'Waiting Period: 14 days',
    ],
    ctaUrl: 'https://www.petsbest.com',
    websiteUrl: 'https://www.petsbest.com',
  },
  {
    id: 10,
    name: 'Figo',
    logo: null,
    ourScore: 9.0,
    trustpilotScore: null,
    brandReputation: 8.8,
    popularityScore: 8.0,
    reviewCount: null,
    highlight:
      'Modern pet insurer with 100% reimbursement option and a user-friendly app (including live vet chat), plus available add-ons for wellness and exam fee coverage.',
    productTypes: ['pet_insurance'],
    amount: '$20 - $100/month',
    amountRange: 'under_10k',
    goodDetails: [
      'Provides 100% reimbursement option and unlimited annual benefits option for maximum coverage',
      'Mobile app (Pet Cloud) includes 24/7 live vet chat and easy claim filing',
      'Short 1-day waiting period for injuries caused by accidents (one of the shortest available)',
      'Online Application: Yes',
    ],
    badDetails: [
      'Routine care not covered without purchasing optional Wellness Powerup add-on',
      'Charges extra for exam fee coverage (not included by default)',
      'Not available in all states (coverage area still expanding)',
      'Waiting Period: 1 day (accidents), 14 days (illness)',
    ],
    ctaUrl: 'https://www.figopetinsurance.com',
    websiteUrl: 'https://www.figopetinsurance.com',
  },
];
