import type { Brand } from './lendersData';

export const studentLoansData: Brand[] = [
  {
    id: 1,
    name: 'SoFi',
    logo: '/images/table/Sofi-logo.svg',
    ourScore: 9.7,
    trustpilotScore: 9.2,
    brandReputation: 9.8,
    popularityScore: 9.6,
    reviewCount: 12500,
    highlight: 'Low rates and member benefits for student loan refinancing',
    productTypes: ['private', 'refinance'],
    minCreditScore: 'good',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '10k_50k',
    amount: '$5K - $500K',
    goodDetails: [
      'Rate Range: 2.99% - 9.99%',
      'No Fees: Yes',
      'Unemployment Protection: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 650',
      'Income Requirement: $45,000+',
      'Co-signer: May be required',
      'Graduation Required: Yes',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 2,
    name: 'Credible',
    logo: '/images/table/Credible-logo.svg',
    ourScore: 9.6,
    trustpilotScore: 9.0,
    brandReputation: 9.4,
    popularityScore: 9.2,
    reviewCount: 11200,
    highlight: 'Compare student loan rates from multiple lenders',
    productTypes: ['private', 'refinance'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '10k_50k',
    amount: '$1K - $500K',
    goodDetails: [
      'Multiple Lenders: Yes',
      'Prequalification: No hard pull',
      'Rate Comparison: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 600',
      'APR Range: 3.99% - 12.99%',
      'Co-signer: May be required',
      'Graduation Required: Yes',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 3,
    name: 'LendingTree',
    logo: '/images/table/LendingTree-logo.svg',
    ourScore: 9.5,
    trustpilotScore: 9.1,
    brandReputation: 9.5,
    popularityScore: 9.3,
    reviewCount: 15200,
    highlight: 'Compare student loan offers from top lenders',
    productTypes: ['private', 'refinance'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '10k_50k',
    amount: '$1K - $500K',
    goodDetails: [
      'Multiple Offers: Yes',
      'All Loan Types: Available',
      'Fast Comparison: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 600',
      'APR Range: 3.99% - 12.99%',
      'Co-signer: May be required',
      'Graduation Required: Yes',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 4,
    name: 'NerdWallet',
    logo: '/images/brands-logos/nerd-wallet-logo.svg',
    ourScore: 9.4,
    trustpilotScore: 8.8,
    brandReputation: 9.6,
    popularityScore: 9.5,
    reviewCount: 18500,
    highlight: 'Expert guidance on student loans and refinancing',
    productTypes: ['private', 'refinance'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '10k_50k',
    amount: '$1K - $500K',
    goodDetails: [
      'Expert Reviews: Yes',
      'Comparison Tools: Yes',
      'Educational Resources: Yes',
      'Free Service: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 600',
      'APR Range: Varies by lender',
      'Not a Direct Lender: Marketplace',
      'Graduation Required: Yes',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 5,
    name: 'LightStream',
    logo: '/images/table/LightStream-logo.svg',
    ourScore: 9.3,
    trustpilotScore: 9.4,
    brandReputation: 9.6,
    popularityScore: 9.4,
    reviewCount: 9800,
    highlight: 'Best rates for borrowers with excellent credit',
    productTypes: ['private', 'refinance'],
    minCreditScore: 'excellent',
    minRevenue: '20k_30k',
    minTimeInBusiness: '1_2',
    amountRange: '50k_100k',
    amount: '$5K - $500K',
    goodDetails: [
      'Rate Range: 2.99% - 8.99%',
      'No Fees: Yes',
      'Same-Day Funding: Available',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 720',
      'Income Requirement: $50,000+',
      'Co-signers: Not allowed',
      'Graduation Required: Yes',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 6,
    name: 'Fundera',
    logo: '/images/brands-logos/fundera-logo.svg',
    ourScore: 9.2,
    trustpilotScore: 9.0,
    brandReputation: 9.2,
    popularityScore: 9.0,
    reviewCount: 8400,
    highlight: 'Expert guidance to find the best student loan',
    productTypes: ['private', 'refinance'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '10k_50k',
    amount: '$1K - $500K',
    goodDetails: [
      'Expert Guidance: Yes',
      'Multiple Lenders: Yes',
      'Rate Comparison: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 600',
      'APR Range: 3.99% - 12.99%',
      'Co-signer: May be required',
      'Graduation Required: Yes',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 7,
    name: 'Lendio',
    logo: '/images/brands-logos/lendio-logo.svg',
    ourScore: 9.1,
    trustpilotScore: 8.6,
    brandReputation: 9.0,
    popularityScore: 8.8,
    reviewCount: 9200,
    highlight: 'Access to multiple student loan lenders',
    productTypes: ['private', 'refinance'],
    minCreditScore: 'fair',
    minRevenue: '10k_20k',
    minTimeInBusiness: '6m_1y',
    amountRange: '10k_50k',
    amount: '$1K - $500K',
    goodDetails: [
      'Multiple Lenders: Yes',
      'One Application: Yes',
      'Fast Matching: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 600',
      'APR Range: 3.99% - 12.99%',
      'Co-signer: May be required',
      'Graduation Required: Yes',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
  {
    id: 8,
    name: 'Biz2Credit',
    logo: '/images/brands-logos/Biz2credit-logo.svg',
    ourScore: 9.0,
    trustpilotScore: 9.4,
    brandReputation: 9.7,
    popularityScore: 9.6,
    reviewCount: 15146,
    highlight: 'Fast approval for student loan refinancing',
    productTypes: ['refinance'],
    minCreditScore: 'good',
    minRevenue: '20k_30k',
    minTimeInBusiness: '1_2',
    amountRange: '50k_100k',
    amount: '$10K - $500K',
    goodDetails: [
      'Fast Approval: 24 hours',
      'Competitive Rates: Yes',
      'No Fees: Yes',
      'Online Application: Yes',
    ],
    badDetails: [
      'Minimum Credit Score: 650',
      'Income Requirement: $50,000+',
      'Graduation Required: Yes',
      'Existing Loans: Must qualify',
    ],
    ctaUrl: '#',
    websiteUrl: '#',
  },
];
